<?xml version="1.0"?>
<robot name="ball_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================== -->
  <!-- XACRO PROPERTIES -->
  <!-- ========================== -->

  <xacro:property name="base_length" value="0.25"/>
  <xacro:property name="base_width"  value="0.25"/>
  <xacro:property name="base_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.04"/>
  <xacro:property name="wheel_width"  value="0.03"/>

  <xacro:property name="caster_radius" value="0.025"/>

  <xacro:property name="finger_length" value="0.12"/>
  <xacro:property name="finger_width"  value="0.02"/>
  <xacro:property name="finger_height" value="0.06"/>

  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.02"/>

  <!-- Colors -->
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="grey"><color rgba="0.7 0.7 0.7 1"/></material>

  <!-- ========================== -->
  <!-- BASE LINK -->
  <!-- ========================== -->

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_height/2}"/>
      <inertia ixx="0.02" iyy="0.02" izz="0.02"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- ========================== -->
  <!-- WHEEL MACRO -->
  <!-- ========================== -->

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.00016" iyy="0.00016" izz="0.00016"
                 ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate wheels -->
  <xacro:wheel name="rear_left_wheel"  x="-0.05" y="0.12"/>
  <xacro:wheel name="rear_right_wheel" x="-0.05" y="-0.12"/>

  <!-- ========================== -->
  <!-- FRONT CASTER -->
  <!-- ========================== -->

  <link name="front_caster">
    <visual>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <geometry><sphere radius="${caster_radius}"/></geometry>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.000009" iyy="0.000009" izz="0.000009"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="0.09 0 ${caster_radius}"/>
  </joint>

  <!-- ========================== -->
  <!-- LIDAR -->
  <!-- ========================== -->

  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="${lidar_radius}" length="${lidar_height}"/></geometry>
      <material name="black"/>
    </visual>

    <collision>
      <geometry><cylinder radius="0.03" length="${lidar_height}"/></geometry>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.000005" iyy="0.000005" izz="0.000008"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.10"/>
  </joint>

</robot>
