<?xml version="1.0"?>
<robot name="ball_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================================================= -->
  <!-- PARAMETERS -->
  <!-- ========================================================= -->
  <xacro:property name="base_length" value="0.30"/>
  <xacro:property name="base_width"  value="0.25"/>
  <xacro:property name="base_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.04"/>
  <xacro:property name="wheel_width"  value="0.02"/>

  <xacro:property name="caster_radius" value="0.025"/>

  <xacro:property name="finger_length" value="0.12"/>
  <xacro:property name="finger_width"  value="0.02"/>
  <xacro:property name="finger_height" value="0.08"/>

  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.02"/>

  <!-- Colors -->
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="grey"><color rgba="0.6 0.6 0.6 1"/></material>

  <!-- ========================================================= -->
  <!-- BASE LINK -->
  <!-- ========================================================= -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_height/2}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_height/2}"/>
      <inertia ixx="0.02" ixy="0" ixz="0"
               iyy="0.02" iyz="0" izz="0.02"/>
    </inertial>
  </link>

  <!-- ========================================================= -->
  <!-- WHEEL MACRO -->
  <!-- ========================================================= -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0"
                 iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Rear wheels -->
  <xacro:wheel name="rear_left_wheel"  x="-0.10" y="0.12"/>
  <xacro:wheel name="rear_right_wheel" x="-0.10" y="-0.12"/>

  <!-- ========================================================= -->
  <!-- CENTER CASTER WHEEL (ball-like support) -->
  <!-- ========================================================= -->
  <link name="caster_wheel">
    <visual>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><sphere radius="${caster_radius}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0"
               iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.10 0 ${caster_radius}"/>
  </joint>

  <!-- ========================================================= -->
  <!-- LEFT + RIGHT GRIPPER FINGERS -->
  <!-- ========================================================= -->
  <link name="left_finger">
    <visual>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <link name="right_finger">
    <visual>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- Joints for the gripper fingers -->
  <joint name="left_finger_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_finger"/>
    <origin xyz="0.15 0.06 0.06"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
  </joint>

  <joint name="right_finger_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_finger"/>
    <origin xyz="0.15 -0.06 0.06"/>
    <axis xyz="0 0 -1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
  </joint>

  <!-- ========================================================= -->
  <!-- LIDAR -->
  <!-- ========================================================= -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.15"/>
  </joint>

</robot>
