<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="push_bot">

  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="wheel_width" value="0.04"/>

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="6.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      <origin xyz="0 0 ${base_height/2}"/>
    </inertial>
  </link>

  <!-- left wheel -->
  <link name="wheel_left_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <!-- right wheel (copy) -->
  <link name="wheel_right_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"/>
    </inertial>
  </link>

  <!-- wheel joints -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0 ${base_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0 -${base_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- simple front push plate -->
  <link name="bumper_link">
    <visual>
      <geometry>
        <box size="${base_length*0.8} 0.02 ${base_height*0.4}" />
      </geometry>
      <origin xyz="${base_length/2 - 0.05} 0 ${base_height*0.2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length*0.8} 0.02 ${base_height*0.4}" />
      </geometry>
      <origin xyz="${base_length/2 - 0.05} 0 ${base_height*0.2}" rpy="0 0 0"/>
    </collision>
  </link>

  <joint name="bumper_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bumper_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
